#!/usr/bin/env bash
# This script displays information about subdomains using DNS lookup

# Function to fetch DNS information for a given subdomain
# Arguments:
#   $1: Domain name
#   $2: Subdomain name
dns_config () {
    # Store domain and subdomain names
    local domain="$1"
    local subdomain="$2"
    
    # Fetch DNS information for the subdomain
    local script
    script=$(dig "$subdomain.$domain" +short)

    local record
    record=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION/{getline;print}')
    
    # Check if the subdomain exists
    if [ -n "$script" ]; then
        # Display information if subdomain exists
        echo "The subdomain $subdomain is a $record record and points to $script"
    else
        # Display message if subdomain does not exist
        echo "The subdomain $subdomain does not exist."
    fi
}

# Main script
if [ "$#" == 1 ]; then
    # Display information for common subdomains if only domain name is provided
    dns_config "$1" "www"
    dns_config "$1" "lb-01"
    dns_config "$1" "web-01"
    dns_config "$1" "web-02"
elif [ "$#" == 2 ]; then
    # Display information for the provided subdomain and domain name
    dns_config "$1" "$2"
fi
