#!/usr/bin/env bash
# Write a Bash script that will display information about the subdomains

# Function to fetch DNS information for a given subdomain
# Arguments:
#   $1: Domain name
#   $2: Subdomain name
dns_config () {
    # Fetch DNS information for the subdomain
    local script
    script=$(dig +short "$2.$1")
    
    # Check if the subdomain exists
    if [ -n "$script" ]; then
        # Determine the DNS record type
        local record_type
        record_type=$(dig "$2.$1" | awk '/ANSWER SECTION/{getline; print $4}')
        
        # Display information if subdomain exists
        echo "The subdomain $2 is a $record_type record and points to $script"
    else
        # Display message if subdomain does not exist
        echo "The subdomain $2 does not exist."
    fi
}

# Main script
if [ "$#" == 1 ]; then
    # Display information for common subdomains if only domain name is provided
    dns_config "$1" "www"
    dns_config "$1" "lb-01"
    dns_config "$1" "web-01"
    dns_config "$1" "web-02"
elif [ "$#" == 2 ]; then
    # Display information for the provided subdomain and domain name
    dns_config "$1" "$2"
fi
