#!/usr/bin/env bash
# This script configures an Ubuntu machine to meet the specified requirements for Nginx.

# Update the package repositories and upgrade existing packages
sudo apt update

# Installing Nginx
sudo apt install -y nginx

# Verify Nginx is listening on port 80
sudo ufw allow 'Nginx HTTP'

# Create a basic HTML file with the required content
echo "Hello World!" | tee /var/www/html/index.nginx-debian.html

# Restart Nginx without using systemctl
sudo service nginx start
