#!/usr/bin/env bash
# A script that customizes a 404 error page

# Updating packages
sudo apt-get update

# Installing nginx
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

replacement_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/LawsonLawson permanent;"

sudo sed -i "s/server_name _;/$replacement_string/" /etc/nginx/sites_enabled/default

# customize an error page (404)
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

replacement_string="list 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.hmtl {\n\troot \/var/www/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$replacement_string/" /etc/nginx/sites-enabled/default

sudo service nginx restart
