#!/usr/bin/env bash
# This script installs and configure HAProxy on lb-01 server
# It configures HAProxy to send traffic to web-01 and web-02 servers
# It distribute requests using a roundrobin algorithm
# It makes sure that HAProxy can be managed via an init script

# Getting updates
sudo apt-get -y update

# Installing and configuring HAproxy lb-01 server.
apt-get -y install haproxy

# Editing configuration file
server_config=\
"
frontend  LawsonLawson_frontend
        bind *:80
        mode http
        default_backend LawsonLawson_backend
backend LawsonLawson_backend
        balance roundrobin
        server 530392-web-01 3.89.160.178:80 check
        server 530392-web-02 35.175.63.135:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enabling haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restarting the HAproxy to apply changes
sudo service haproxy restart
