#!/usr/bin/env bash
# This script configures NGINX to listen on port 80 (sweet and short version)
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
kill -9 "$(cat /run/nginx.pid)"
