#!/usr/bin/env bash
# a Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59
iterations=0
hour=0
while ((iterations < 779)); do
	echo "Hour: $hour"
	minute=0
	while ((minute < 60)); do
		echo "$minute"
		((minute++))
		((iterations++))
	done
	((hour++))
done
