#!/usr/bin/env bash
# a Bash script that displays:
# The content of the current directory
# Where only the part of the name after the first dash is displayed
for file in *; do
	if [ -f "$file" ] && [ ! -h "$file" ]; then
		name_of_file=$(echo "$file" | cut -d'-' -f2-)
		echo "$name_of_file"
	fi
done
