#!/usr/bin/env bash

# Define the name for the private key
private_key="school"

# Define the number of bits for the RSA key
bits="4096"

# Define the passphrase
passphrase="betty"

# Now generate the RSA key pair
ssh-keygen -t rsa -b "$bits" -f "$private_key" -N "$passphrase"
